version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: ecommerce_analytics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: