name: E-commerce Data Analysis CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyspark pytest
    
    - name: Run unit tests
      run: pytest tests/
    
    - name: Static code analysis
      run: |
        pip install flake8
        flake8 .
    
    - name: Build Docker image
      run: docker build -t ecommerce-analysis .
    
    - name: Push to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push yourusername/ecommerce-analysis